services:
  phpfpm83:
    image: registry.cn-beijing.aliyuncs.com/yangxiuchuan/php:8.3.33-swoole5.1.8
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ./php83/etc/php.ini:/usr/local/etc/php/php.ini
      - ./php83/supervisor:/etc/supervisor.d
      - ${WORK_DIR}:/var/www
    container_name: phpfpm83
    networks:
      docker_services_net:
        ipv4_address: 192.168.10.83
networks:
  docker_services_net:
    external: true
